# Generated by Django 4.2.1 on 2023-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_prescription_note_prescription_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
