# Generated by Django 4.2.1 on 2023-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_doctor_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_fees',
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bmdc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='followup',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='isFollowup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='clinic_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='doctor_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
