# Generated by Django 4.2.1 on 2023-05-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctor_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='workspace',
            new_name='workplace',
        ),
    ]
