# Generated by Django 4.2.1 on 2023-05-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_slots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
