# Generated by Django 4.2.1 on 2023-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appointment_address_appointment_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='next_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
